### ISSUE TITLE
Question about the touch driver

### ISSUE THREAD

**Issue by Sebwap** [pimoroni/hyperpixel2r-python#5]
Hello,

Does the touch driver manage only "touch" action or also slide ?
Does it need a desktop environment or rasbian OS lite is ok ?

Many thanks !

**Comment by Gadgetoid** [comment]
The touch driver only gets touch events, it doesn't attempt to interpret them at all for gestures. The python library is entirely self-contained, so no desktop environment is required.

**Comment by Sebwap** [comment]
Ok so i assume to have to try to interpret successives coordinates to detect sliding ...

Quite challenging !
Thanks for your reply !
